version: '3'
services:
  catcafe:
    build: .
    container_name: catcafe
    ports:
      - "8000:8000"
    environment:
      - UWSGI_INI=/home/ctf/uwsgi.ini
      - LISTEN_PORT=8000
    restart: always
